[package]
name = "impl-vol"
version = "0.0.1"
authors = ["Dariusz Depta <depta@engos.software>"]
description = "Implied volatility"
documentation = "https://docs.rs/impl-vol"
repository = "https://github.com/DariuszDepta/impl-vol.git"
license = "MIT"
edition = "2018"

[dependencies]
